version: "3"

services:
  # Django
  django:
    build: .
    container_name: django
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app/
    links:
      - database
    depends_on:
      - database
  # Django database
  database:
    image: mysql:latest
    container_name: database
    environment:
      MYSQL_DATABASE: our_projects_database
      MYSQL_USER: root
      MYSQL_PASSWORD: ba81906377
      MYSQL_ROOT_PASSWORD: ba81906377
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
  # Frontend
  frontend:
    build: frontend/
    container_name: frontend
    command: npm run serve
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - django
  # Phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - database
    depends_on:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 300M
    restart: always
    ports:
      - "7000:80"
  # # Nginx server
  # nginx_server:
  #   image: nginx:latest
  #   container_name: nginx_server
  #   ports:
  #     - "80:80"
  #   restart: always
  #   volumes:
  #     - ./nginx_server.conf:/etc/nginx/nginx.conf
volumes:
  mysql_data:
