version: "3"

services:
  # Django server
  django:
    build: .
    container_name: django
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app/
    links:
      - db
    depends_on:
      - db
  # Django database
  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_DATABASE: our_projects_db
      MYSQL_ROOT_PASSWORD: ba81906377
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./mysql-volume:/var/lib/mysql
  # Frontend
  frontend:
    build: frontend/
    container_name: frontend
    command: npm run serve
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - django
  # Phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    links:
      - db
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 300M
    restart: always
    ports:
      - "7000:80"
