# Generated by Django 4.0.6 on 2022-07-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='stack',
            field=models.CharField(default='', max_length=320),
            preserve_default=False,
        ),
    ]
